// Gender Enum
export const GENDER_MALE = 'MALE'
export const GENDER_FEMALE = 'FEMALE'
export const GENDER_BOTH = 'BOTH'
export const ALL_GENDERS = [GENDER_MALE, GENDER_FEMALE, GENDER_BOTH]

// Status Enum
export const STATUS_DRAFT = 'DRAFT'
export const STATUS_SUBMITTED = 'SUBMITTED'
export const STATUS_REJECTED = 'REJECTED'
export const STATUS_FINISHED = 'FINISHED'
export const STATUS_ONGOING = 'ONGOING'
export const ALL_STATUS = [
  STATUS_DRAFT,
  STATUS_SUBMITTED,
  STATUS_REJECTED,
  STATUS_FINISHED,
  STATUS_ONGOING
]
