name: PRODUCTION - Keep Supabase DB up
on:
  schedule:
    - cron: '0 0 * * *' # every day at 12AM
jobs:
  production:
    name: Production job runner
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'
    steps:
      - shell: bash
        run: curl -m 300 -X GET https://app.toud.com.br/api/jobs/ping

